x-veld:
  executable:
    about:
      description: "dummy veld for testing and showcasing"
    input:
      a:
        path: /veld/input/a/data.xml
        format: "xml"
        kind: "dummy data"
      b:
        path: /veld/input/b/schema.xsd
        format: "xsd"
        kind: "dummy data"
        optional: true
    output:
      path: /veld/output/result.sh
      format: "sh"
      kind: "dummy data"

services:
  veld:
    build: .
    volumes:
      - ./src/:/veld/executable/
    command: bash /veld/executable/validate.sh


