x-veld:
  executable:
    about:
      description: "example veld for testing and showcasing"
    topics: "data validation"
    input:
      a:
        type: "files"
        format: "xml"
        content: "dummy data"
        path: /veld/input/data.xml
      b:
        type: "files"
        format: "xsd"
        content: "dummy data"
        path: /veld/input/schema.xsd
        optional: true
    output:
      type: "files"
      format: "txt"
      content: "dummy data"
      path: /veld/output/result.txt

services:
  veld:
    build: .
    volumes:
      - ./validate.sh:/veld/executable/validate.sh
    command: bash /veld/executable/validate.sh


